@host=http://localhost:5250
GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTliYzU2OS01YjFkLTRmZWEtOTlmYi0yODJiMGRhYmIxNWQiLCJnaXZlbl9uYW1lIjoiS2l2YW5jIiwiZmFtaWx5X25hbWUiOiJUdXJrZXIiLCJhdWQiOiJCdWJlckRpbm5lciIsImp0aSI6ImMzZjZkODE3LTlkNjktNGIwOS1iZDM5LTk3ODBiMjkwZDA2OCIsImV4cCI6MTcwNDQ1OTA3NSwiaXNzIjoiQnViZXJEaW5uZXIifQ.HT5Y9Wm_E35UiJon1zTcx5Xq4HAsFu5D6uztg1mxUns
